C     g++/icc is messing with fortran functions returning complex numbers,
C     thus wrapping them around
C
C     Copyright (C), Sergei Nikolaev, 1992-2006, http://cvmlib.com
C

      SUBROUTINE VCDOTU (DOT, N, X, INCX, Y, INCY)
CDEC$ IF DEFINED (FTN_EXPORTS)
CDEC$     ATTRIBUTES DLLEXPORT::VCDOTU
CDEC$ ENDIF
      INTEGER*4  N, INCX, INCY
      COMPLEX*8  X(*), Y(*), DOT
      COMPLEX*8  CDOTU

      DOT = CDOTU(N, X, INCX, Y, INCY)

      RETURN
      END !SUBROUTINE VCDOTU

      SUBROUTINE VZDOTU (DOT, N, X, INCX, Y, INCY)
CDEC$ IF DEFINED (FTN_EXPORTS)
CDEC$     ATTRIBUTES DLLEXPORT::VZDOTU
CDEC$ ENDIF
      INTEGER*4  N, INCX, INCY
      COMPLEX*16 X(*), Y(*), DOT
      COMPLEX*16 ZDOTU

      DOT = ZDOTU(N, X, INCX, Y, INCY)

      RETURN
      END !SUBROUTINE VZDOTU

      SUBROUTINE VCDOTC (DOT, N, X, INCX, Y, INCY)
CDEC$ IF DEFINED (FTN_EXPORTS)
CDEC$     ATTRIBUTES DLLEXPORT::VCDOTC
CDEC$ ENDIF
      INTEGER*4  N, INCX, INCY
      COMPLEX*8  X(*), Y(*), DOT
      COMPLEX*8  CDOTC

      DOT = CDOTC(N, X, INCX, Y, INCY)

      RETURN
      END !SUBROUTINE VCDOTC

      SUBROUTINE VZDOTC (DOT, N, X, INCX, Y, INCY)
CDEC$ IF DEFINED (FTN_EXPORTS)
CDEC$     ATTRIBUTES DLLEXPORT::VZDOTC
CDEC$ ENDIF
      INTEGER*4  N, INCX, INCY
      COMPLEX*16 X(*), Y(*), DOT
      COMPLEX*16 ZDOTC

      DOT = ZDOTC(N, X, INCX, Y, INCY)

      RETURN
      END !SUBROUTINE VZDOTC
