#ifndef TARQUIN_EXCEPTION_INCLUDED
#define TARQUIN_EXCEPTION_INCLUDED

#include <exception>
#include <string>
#include <stdarg.h>

namespace tarquin
{

/*!
 * \brief Base class for all exceptions generated by TARQUIN.
 */
class Exception : public std::exception
{
	public:

		Exception() { }

		~Exception() throw() { }

		Exception(const char* szfmt, ... ) 
		{
			va_list lst;
			va_start(lst, szfmt);
			Message(szfmt, lst);
			va_end(lst);
		}

		const char* what() const throw()
		{
			return m_msg.c_str();
		}

	protected:

		void Message(const char* szfmt, va_list lst) 
		{
			char szBuffer[2048];
			vsnprintf(szBuffer, 2048, szfmt, lst);
			m_msg = szBuffer;
		}


	protected:

		//! The message that will be contained in the exception.
		std::string m_msg;
};

}

#endif
